### ISSUE TITLE
How can I learn more about this branch?

### ISSUE THREAD

**Issue by abdulhannanali** [afisch93/Anxiety-Detection#1]
Hey Adam! That seems a cool project. What things do I need to learn to make a project similar to this one? Is this based on AI or only Image Recognition?

**Comment by ajfisch** [comment]
Hi @abdulhannanali,

Thanks for checking this out. This project was a quick final project for a computer vision class I took as an undergrad in 2014. Primarily it uses image processing. There's not much AI, apart from a small Hidden Markov Model at the end (which isn't the most sound... quite little data).

The report we wrote is included in this repo -- you can check that out for more details. The code is all matlab, so it might be hard to run if you don't have a license.
